// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5112.Magni.subsystems;

import org.usfirst.frc5112.Magni.Robot;
import org.usfirst.frc5112.Magni.RobotMap;
import org.usfirst.frc5112.Magni.commands.*;

import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Drivetrain extends Subsystem {
	private final SpeedController rightBackDriveTrainMotor = RobotMap.rightBackDriveTrainMotor;
	private final SpeedController rightFrontDriveTrainMotor = RobotMap.rightFrontDriveTrainMotor;
	private final SpeedController leftBackDriveTrainMotor = RobotMap.leftBackDriveTrainMotor;
	private final SpeedController leftFrontDriveTrainMotor = RobotMap.leftFrontDriveTrainMotor;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        rightBackDriveTrainMotor.set(0);
        rightFrontDriveTrainMotor.set(0);
        leftBackDriveTrainMotor.set(0);
        leftFrontDriveTrainMotor.set(0);
        
    	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    public void stop() {
    	rightBackDriveTrainMotor.set(0);
        rightFrontDriveTrainMotor.set(0);
        leftBackDriveTrainMotor.set(0);
        leftFrontDriveTrainMotor.set(0);
    }
    public void forward(double speed) {
    	rightBackDriveTrainMotor.set(speed);
        rightFrontDriveTrainMotor.set(speed);
        leftBackDriveTrainMotor.set(-speed);
        leftFrontDriveTrainMotor.set(-speed);
    }
    public void backward(double speed) {
    	rightBackDriveTrainMotor.set(-speed);
        rightFrontDriveTrainMotor.set(-speed);
        leftBackDriveTrainMotor.set(speed);
        leftFrontDriveTrainMotor.set(speed);
    }
    public void rotateClockwise(double speed) {
    	rightBackDriveTrainMotor.set(speed);
        rightFrontDriveTrainMotor.set(speed);
        leftBackDriveTrainMotor.set(speed);
        leftFrontDriveTrainMotor.set(speed);
    }
    public void rotateCounterClockwise(double speed) {
    	rightBackDriveTrainMotor.set(-speed);
        rightFrontDriveTrainMotor.set(-speed);
        leftBackDriveTrainMotor.set(-speed);
        leftFrontDriveTrainMotor.set(-speed);
    }
}