// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5112.Magni;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.hal.CanTalonSRX;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static DigitalInput obstacleArmLimitSwitch;
    public static SpeedController obstacleArmMotor;
    public static SpeedController leftIntakeMotor;
    public static SpeedController rightIntakeMotor;
    public static SpeedController leftShooterMotor;
    public static SpeedController rightShooterMotor;
    public static SpeedController rightFrontDriveTrainMotor;
    public static SpeedController rightBackDriveTrainMotor;
    public static SpeedController leftFrontDriveTrainMotor;
    public static SpeedController leftBackDriveTrainMotor;
    public static SpeedController kickerMotor;
    

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    	// I remember everything...
        obstacleArmLimitSwitch = new DigitalInput(0);
        LiveWindow.addSensor("Obstacle Arm", "Limit Switch", obstacleArmLimitSwitch);
        obstacleArmMotor = new Victor();
        leftIntakeMotor = new CANTalon();
        rightIntakeMotor = new Victor();
        leftShooterMotor = new Victor();
        rightShooterMotor = new CANTalon();
        rightFrontDriveTrainMotor = new CANTalon();
        rightBackDriveTrainMotor = new CANTalon();
        leftFrontDriveTrainMotor = new CANTalon();
        leftBackDriveTrainMotor = new CANTalon();
        kickerMotor = new Victor();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
